# -*- coding: utf-8 -*-
"""TestScripts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FW7wugpqXrL33yW1ZSLzDJ9JwJUtcyzr
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogleLandingPage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_gmailButton(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(773, 816)
    self.driver.find_element(By.LINK_TEXT, "Gmail").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#gbwa .gb_d")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Aa")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()

  def test_imFeelingLuckyButton(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(773, 816)
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .RNmpXc").click()

  def test_googleSearchTest(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(770, 816)
    self.driver.find_element(By.ID, "APjFqb").send_keys("Selenium IDE")
    self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()

try:
  class TestGoogleLandingPage():
    def setup_method(self, method):
      self.driver = webdriver.Chrome()
      self.vars = {}

    def teardown_method(self, method):
      self.driver.quit()

    def test_gmailButton(self):
      self.driver.get("https://www.google.com/")
      self.driver.set_window_size(773, 816)
      self.driver.find_element(By.LINK_TEXT, "Gmail").click()
      element = self.driver.find_element(By.CSS_SELECTOR, "#gbwa .gb_d")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, "body")
      actions = ActionChains(self.driver)
      actions.move_to_element(element, 0, 0).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Aa")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, "body")
      actions = ActionChains(self.driver)
      actions.move_to_element(element, 0, 0).perform()

    def test_imFeelingLuckyButton(self):
      self.driver.get("https://www.google.com/")
      self.driver.set_window_size(773, 816)
      self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .RNmpXc").click()

    def test_googleSearchTest(self):
      self.driver.get("https://www.google.com/")
      self.driver.set_window_size(770, 816)
      self.driver.find_element(By.ID, "APjFqb").send_keys("Selenium IDE")
      self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(1)").click()
      self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
except Exception as e:
    print(f"Error during test suite execution: {str(e)}")